version: '3'
services:
  Plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
    volumes:
      - ./plex/config:/config
      - ./plex/tvseries:/tv
      - ./plex/movies:/movies
    ports:
      - 32400:32400
    networks:
      - docker-shared-network
    restart: unless-stopped
  Overseerr:
    image: lscr.io/linuxserver/overseerr:latest
    container_name: overseerr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
    volumes:
      - ./overseerr/config:/config
    ports:
      - 5055:5055
    networks:
      - docker-shared-network
    restart: unless-stopped
  Radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
      - PROFILE_NAME=FR
      - RESOLUTION_PROFILE=1080p
    volumes:
      - ./radarr/config:/config
      - ./radarr/movies:/movies
    ports:
      - 7878:7878
    networks:
      - docker-shared-network
    restart: unless-stopped
  Sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
      - UMASK_SET=022
      - PROFILE_NAME=FR
      - RESOLUTION_PROFILE=1080p
    volumes:
      - ./sonarr/config:/config
      - ./sonarr/tv:/tv
    ports:
      - 8989:8989
    networks:
      - docker-shared-network
    restart: unless-stopped
networks: 
  docker-shared-network:
    external: true