version: '3'
services:
  Bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ./bazarr/config:/config
    ports:
      - 6767:6767
    networks:
      - docker-shared-network
    restart: unless-stopped
  Prowlarr:
    image: lscr.io/linuxserver/prowlarr:develop
    container_name: prowlarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ./prowlarr/config:/config
    ports:
      - 9696:9696
    networks:
      - docker-shared-network
    restart: unless-stopped
  swag:
    image: linuxserver/swag
    container_name: swag
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/letsencrypt:/config/letsencrypt
      - /etc/swag:/config
      - /etc/nginx:/config/nginx
      - /etc/nzbget:/config/nzbget
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - URL=projectdocker.duckdns.org
      - VALIDATION=duckdns
      - DUCKDNSTOKEN=${DUCKDNSTOKEN}
    networks:
      - docker-shared-network
    restart: unless-stopped
networks: 
  docker-shared-network:
    external: true